import React, { useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Typography,
  Box,
  TextField,
  IconButton,
  Alert,
  Tabs,
  Tab,
  Paper,
} from '@mui/material';
import { Close, ContentPaste, QrCodeScanner, FlipCameraIos } from '@mui/icons-material';
import QrReader from 'react-qr-scanner';

interface LoadModalProps {
  open: boolean;
  onClose: () => void;
  onLoadSchedule: (encodedString: string) => void;
}

const LoadModal: React.FC<LoadModalProps> = ({ open, onClose, onLoadSchedule }) => {
  const [encodedString, setEncodedString] = useState<string>('');
  const [activeTab, setActiveTab] = useState<number>(0);
  const [scanError, setScanError] = useState<string>('');
  const [cameraId, setCameraId] = useState<string>('environment'); // Default to back camera
  const [availableCameras, setAvailableCameras] = useState<MediaDeviceInfo[]>([]);

  // Suppress console warnings from react-qr-scanner
  React.useEffect(() => {
    const originalWarn = console.warn;
    console.warn = (...args) => {
      if (args[0] && typeof args[0] === 'string' && 
          (args[0].includes('defaultProps') || args[0].includes('legacyMode'))) {
        return; // Suppress these specific warnings
      }
      originalWarn.apply(console, args);
    };
    
    return () => {
      console.warn = originalWarn;
    };
  }, []);

  const handlePasteFromClipboard = async () => {
    try {
      const text = await navigator.clipboard.readText();
      setEncodedString(text);
    } catch (error) {
      console.error('Failed to read clipboard:', error);
    }
  };

  const handleLoad = () => {
    if (!encodedString || (typeof encodedString === 'string' && !encodedString.trim())) {
      alert('Please paste an encoded schedule string or scan a QR code.');
      return;
    }
    
    // Validate that the string looks like a valid encoded schedule
    try {
      // Try to decode it to see if it's valid base64
      const decoded = atob(encodedString);
      let data;
      
      // Try direct JSON parse first (new format)
      try {
        data = JSON.parse(decoded);
      } catch {
        // Try with URI decoding (legacy format)
        const jsonString = decodeURIComponent(escape(decoded));
        data = JSON.parse(jsonString);
      }
      
      // Check if it has the expected structure
      if (data.t !== 'ssb') {
        alert('Invalid QR code: This doesn\'t appear to be a valid schedule QR code. Please scan a QR code generated by this schedule builder.');
        return;
      }
    } catch (error) {
      alert('Invalid QR code: This doesn\'t appear to be a valid schedule QR code. Please scan a QR code generated by this schedule builder.');
      return;
    }
    
    onLoadSchedule(encodedString);
    onClose();
  };

  const handleClear = () => {
    setEncodedString('');
  };

  const handleScan = (data: any) => {
    if (data) {
      let stringData;
      
      // Handle different data types from QR scanner
      if (typeof data === 'string') {
        stringData = data;
      } else if (data && typeof data === 'object') {
        // If it's an object, try to extract the text property
        if (data.text) {
          stringData = data.text;
        } else if (data.result) {
          stringData = data.result;
        } else {
          // Try to stringify and parse if it's a JSON object
          try {
            stringData = JSON.stringify(data);
          } catch {
            stringData = String(data);
          }
        }
      } else {
        stringData = String(data);
      }
      
      setEncodedString(stringData);
      setScanError('');
    }
  };

  const handleScanError = (err: any) => {
    console.error('QR Scan Error:', err);
    setScanError('Failed to access camera. Please check permissions and try again.');
  };

  const handleTabChange = (event: React.SyntheticEvent, newValue: number) => {
    setActiveTab(newValue);
    setScanError('');
  };

  // Get available cameras
  const getAvailableCameras = async () => {
    try {
      const devices = await navigator.mediaDevices.enumerateDevices();
      const videoDevices = devices.filter(device => device.kind === 'videoinput');
      setAvailableCameras(videoDevices);
      
      // If no cameras found, try to get user media to trigger permission request
      if (videoDevices.length === 0) {
        const stream = await navigator.mediaDevices.getUserMedia({ video: true });
        stream.getTracks().forEach(track => track.stop()); // Stop the stream immediately
        
        // Re-enumerate devices after permission
        const updatedDevices = await navigator.mediaDevices.enumerateDevices();
        const updatedVideoDevices = updatedDevices.filter(device => device.kind === 'videoinput');
        setAvailableCameras(updatedVideoDevices);
      }
    } catch (error) {
      console.error('Error getting cameras:', error);
    }
  };

  // Switch camera
  const switchCamera = () => {
    if (availableCameras.length > 1) {
      const currentIndex = availableCameras.findIndex(camera => camera.deviceId === cameraId);
      const nextIndex = (currentIndex + 1) % availableCameras.length;
      setCameraId(availableCameras[nextIndex].deviceId);
    }
  };

  // Get cameras when QR scanner tab is opened
  React.useEffect(() => {
    if (open && activeTab === 1) {
      getAvailableCameras();
    }
  }, [open, activeTab]);

  // Cleanup when modal closes
  React.useEffect(() => {
    if (!open) {
      setEncodedString('');
      setScanError('');
      setActiveTab(0);
      setCameraId('environment'); // Reset to back camera
    }
  }, [open]);

  return (
    <Dialog 
      open={open} 
      onClose={onClose} 
      maxWidth="sm" 
      fullWidth
      PaperProps={{
        sx: { borderRadius: 2 }
      }}
    >
      <DialogTitle sx={{ 
        display: 'flex', 
        justifyContent: 'space-between', 
        alignItems: 'center',
        pb: 1
      }}>
        <Typography variant="h6" component="div">
          📂 Load Saved Schedule
        </Typography>
        <IconButton onClick={onClose} size="small">
          <Close />
        </IconButton>
      </DialogTitle>

      <DialogContent>
        <Alert severity="info" sx={{ mb: 2 }}>
          Load a saved schedule by pasting an encoded string or scanning a QR code. 
          Make sure you have already loaded the available courses first.
        </Alert>

        <Box sx={{ borderBottom: 1, borderColor: 'divider', mb: 2 }}>
          <Tabs value={activeTab} onChange={handleTabChange} aria-label="load schedule tabs">
            <Tab 
              label="Manual Input" 
              icon={<ContentPaste />} 
              iconPosition="start"
              sx={{ textTransform: 'none' }}
            />
            <Tab 
              label="QR Scanner" 
              icon={<QrCodeScanner />} 
              iconPosition="start"
              sx={{ textTransform: 'none' }}
            />
          </Tabs>
        </Box>

        {/* Manual Input Tab */}
        {activeTab === 0 && (
          <Box sx={{ mb: 3 }}>
            <Typography variant="subtitle2" gutterBottom>
              Encoded Schedule String:
            </Typography>
            <TextField
              multiline
              rows={6}
              value={encodedString}
              onChange={(e) => setEncodedString(e.target.value)}
              fullWidth
              variant="outlined"
              size="small"
              placeholder="Paste the encoded schedule string here..."
              InputProps={{
                sx: { 
                  fontFamily: 'monospace',
                  fontSize: '12px'
                }
              }}
              sx={{ mb: 2 }}
            />
            <Box sx={{ display: 'flex', gap: 1, justifyContent: 'flex-end' }}>
              <Button
                variant="outlined"
                size="small"
                startIcon={<ContentPaste />}
                onClick={handlePasteFromClipboard}
                sx={{ textTransform: 'none' }}
              >
                Paste from Clipboard
              </Button>
              <Button
                variant="outlined"
                size="small"
                onClick={handleClear}
                sx={{ textTransform: 'none' }}
              >
                Clear
              </Button>
            </Box>
          </Box>
        )}

        {/* QR Scanner Tab */}
        {activeTab === 1 && (
          <Box sx={{ mb: 3 }}>
            <Typography variant="subtitle2" gutterBottom>
              Scan QR Code:
            </Typography>
            <Alert severity="info" sx={{ mb: 2, fontSize: '13px' }}>
              <Typography variant="body2">
                <strong>Note:</strong> This scanner only works with QR codes generated by this schedule builder. 
                Scan a QR code that was created when you saved your schedule.
              </Typography>
            </Alert>
            <Paper 
              elevation={2} 
              sx={{ 
                p: 2, 
                textAlign: 'center',
                backgroundColor: '#f5f5f5',
                minHeight: '300px',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'center',
                alignItems: 'center'
              }}
            >
              {scanError ? (
                <Box sx={{ textAlign: 'center' }}>
                  <Typography variant="body2" color="error" sx={{ mb: 2 }}>
                    {scanError}
                  </Typography>
                  <Button 
                    variant="outlined" 
                    onClick={() => setScanError('')}
                    sx={{ textTransform: 'none' }}
                  >
                    Try Again
                  </Button>
                </Box>
              ) : activeTab === 1 ? (
                <Box sx={{ position: 'relative' }}>
                  <QrReader
                    key={`qr-scanner-${cameraId}`}
                    delay={300}
                    onError={handleScanError}
                    onScan={handleScan}
                    style={{ width: '100%', maxWidth: '400px' }}
                    constraints={{
                      video: {
                        deviceId: cameraId
                      }
                    }}
                  />
                  
                  {/* Camera Switch Button */}
                  {availableCameras.length > 1 && (
                    <Button
                      variant="contained"
                      size="small"
                      onClick={switchCamera}
                      startIcon={<FlipCameraIos />}
                      sx={{
                        position: 'absolute',
                        top: '8px',
                        right: '8px',
                        backgroundColor: 'rgba(0, 0, 0, 0.7)',
                        color: 'white',
                        '&:hover': {
                          backgroundColor: 'rgba(0, 0, 0, 0.8)',
                        },
                        minWidth: 'auto',
                        padding: '4px 8px',
                        fontSize: '12px',
                        textTransform: 'none',
                      }}
                    >
                      Switch Camera
                    </Button>
                  )}
                  
                  {/* Camera Info */}
                  {availableCameras.length > 0 && (
                    <Box sx={{ 
                      position: 'absolute', 
                      bottom: '8px', 
                      left: '8px',
                      backgroundColor: 'rgba(0, 0, 0, 0.7)',
                      color: 'white',
                      padding: '4px 8px',
                      borderRadius: '4px',
                      fontSize: '12px'
                    }}>
                      {availableCameras.find(cam => cam.deviceId === cameraId)?.label || 
                       (cameraId === 'environment' ? 'Back Camera' : 'Front Camera')}
                    </Box>
                  )}
                </Box>
              ) : (
                <Box sx={{ p: 4, textAlign: 'center' }}>
                  <Typography variant="body2" color="text.secondary">
                    Switch to QR Scanner tab to start scanning
                  </Typography>
                </Box>
              )}
            </Paper>
            {encodedString && (
              <Alert severity="success" sx={{ mt: 2 }}>
                QR Code scanned successfully! The encoded string has been loaded.
              </Alert>
            )}
          </Box>
        )}

        <Alert severity="warning">
          <Typography variant="body2">
            <strong>Note:</strong> This will replace your current schedule. 
            Make sure you have the correct available courses loaded first.
          </Typography>
        </Alert>
      </DialogContent>

      <DialogActions sx={{ p: 2 }}>
        <Button onClick={onClose} variant="outlined">
          Cancel
        </Button>
        <Button 
          onClick={handleLoad} 
          variant="contained"
          disabled={!encodedString || (typeof encodedString === 'string' && !encodedString.trim())}
          sx={{
            background: 'success.main',
            '&:hover': {
              background: 'success.dark',
            }
          }}
        >
          Load Schedule
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default LoadModal;
